### ISSUE TITLE
[Suggestion] Final Image Size

### ISSUE THREAD

**Issue by bododge** [0000sir/larger-neural-style#3]
First of all great script and I couldn't be more pleased with using it, it is a huge time saver by comparison to using indesign and stopping to re-rig file names which is what I was doing before. I'm still tinkering with how to adjust the overcrop and feather ratios to image size changes. This has opened up the possibilities for everyone. Thank you for creating it. I have a suggestion that could improve the final output:

If you made two merged montage copies of the final image, one from the feathered folder, and a second from the tiles folder, and then overlay the feathered on the merged tiles and you'd get edge to edge pixels without the necessary cropping of the content image in the end. That is what I do in indesign to keep the edges. I realize this might not be super simple to recode the merge process, but would lead to larger sizes, and give the possibility to uprez each of the tiles as well, to create something insane like 3x3, then each tile another 3x3 if that makes sense? (I'm not asking you to include 3x3x9 retiling but am saying you could in theory do it which would be fun) I was coming up with ways to do it with your script but realized the cropping issue would not allow that. I'm not smart enough to rewrite the merge commands, but It looks like you are a genius with imagemagick and could make it happen if you think its a good idea. 

Final note: your script has taught me a few things about how to setup imagemagick and bash variables for drag and drop, thanks for your work!

**Comment by 0000sir** [comment]
I'm sure it will work, I will try it some time. But we're working on other projects, so i'm afraid it won't be soon.

**Comment by bododge** [comment]
Closing since this is not an issue to begin with. Thanks

**Comment by ProGamerGov** [comment]
> If you made two merged montage copies of the final image, one from the feathered folder, and a second from the tiles folder, and then overlay the feathered on the merged tiles and you'd get edge to edge pixels without the necessary cropping of the content image in the end. 

@bododge I have implemented this feature here: https://github.com/ProGamerGov/larger-neural-style Going to push it to the main branch once I have added a few other features.

**Comment by bododge** [comment]
I was looking more into this issue today and I don't think it's possible to have imagemagick succesfully make a montage and then add border padding back in before outputting the image. If there is a way it escapes me. There are montage label and shadow options but nothing for final output size padding or margin.
